--- # Golang Installation
- hosts: 127.0.0.1
  connection: local
  tasks:
  - name: Install Golang
    become: true
    dnf:
      name: golang
      state: latest
  - name: Create go directory
    file:
      path: "{{ ansible_user_dir }}/go"
      state: directory
      owner: "{{ ansible_user_id }}"
      group: "{{ ansible_user_id }}"
      mode: 0755
  - name: Export to .bashrc
    blockinfile:
      path: "{{ ansible_user_dir }}/.bashrc"
      block: |
        export GOPATH=$HOME/go
        export PATH=$PATH:/usr/local/go/bin:$HOME/go/bin
      backup: true
      insertafter: EOF
    when: ansible_facts['user_shell'] == "/bin/bash"
  - name: Export to .zshrc
    blockinfile:
      path: "{{ ansible_user_dir }}/.bashrc"
      block: |
        export GOPATH=$HOME/go
        export PATH=$PATH:/usr/local/go/bin:$HOME/go/bin
      backup: true
      insertafter: EOF
    when: ansible_facts['user_shell'] == "/bin/zsh"
